[tool.poetry]
name = "advent-of-code-20"
version = "0.1.0"
description = ""
authors = ["lordy"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
bpython = "^0.20.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
